name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main   # or master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/echoWasteConnect    # change if your site is in a subfolder
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/README.md
