name: 🚀 Fast Incremental Deploy to Hostinger

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy changed files only
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/echoWasteConnect/
          protocol: ftp
          port: 21
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/README.md
          dangerous-clean-slate: false
          log-level: minimal
