name: 🚀 Deploy ZIP to Hostinger

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          zip -r deploy.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Upload ZIP via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp                         # ✅ valid protocol
          port: 21
          server-dir: /public_html/echoWasteConnect/
          exclude: ''
          local-dir: .
          dangerous-clean-slate: false

      - name: SSH and unzip (requires SSH access)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/youruser/public_html/echoWasteConnect
            unzip -o deploy.zip
            rm deploy.zip
