name: Deploy to Hostinger via SFTP

on:
  push:
    branches:
      - dev   # or main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}   # just IP: 93.127.208.22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/echoWasteConnect/
          protocol: ftps
          port: 21
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/README.md
